"""made city, state and country columns nullable

Revision ID: 008bb1ce50e9
Revises: f29a8a5824e3
Create Date: 2025-08-21 14:58:13.606390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008bb1ce50e9'
down_revision: Union[str, Sequence[str], None] = 'f29a8a5824e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('locations', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('locations', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
