"""added a english title column in generated_user_stories

Revision ID: 0a35ce913efa
Revises: bfaffa5b4b92
Create Date: 2025-10-16 13:58:08.435644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a35ce913efa'
down_revision: Union[str, Sequence[str], None] = 'bfaffa5b4b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('english_title', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_user_stories', 'english_title')
    # ### end Alembic commands ###
