"""271120251638

Revision ID: 13c7344f403c
Revises: 8268dddc3110
Create Date: 2025-11-27 16:38:31.696368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c7344f403c'
down_revision: Union[str, Sequence[str], None] = '8268dddc3110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('added_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'added_on')
    # ### end Alembic commands ###
