"""added unique answer contraint in user_stories_answers

Revision ID: 1970e3fe71d1
Revises: 6857f911fa93
Create Date: 2025-09-10 15:29:18.404674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1970e3fe71d1'
down_revision: Union[str, Sequence[str], None] = '6857f911fa93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_story_question', 'user_stories_answers', ['user_story_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_story_question', 'user_stories_answers', type_='unique')
    # ### end Alembic commands ###
