"""added author relationships LOCAL

Revision ID: 1994e2a8fee9
Revises: 975ff1027044
Create Date: 2025-09-25 13:18:03.079039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1994e2a8fee9'
down_revision: Union[str, Sequence[str], None] = '975ff1027044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'generated_user_stories', 'authors', ['author_id'], ['id'])
    op.add_column('user_stories', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_stories', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.drop_column('user_stories', 'author_id')
    op.drop_constraint(None, 'generated_user_stories', type_='foreignkey')
    op.drop_column('generated_user_stories', 'author_id')
    # ### end Alembic commands ###
