"""made tags and images in generated articles table an empty array be default 091020252147

Revision ID: 20f82e6e599f
Revises: 2b2b1a57d5bd
Create Date: 2025-10-09 21:48:33.701194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f82e6e599f'
down_revision: Union[str, Sequence[str], None] = '2b2b1a57d5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
