"""170220260951 (pressgenai)

Revision ID: 23c37c706819
Revises: 8d92249df95f
Create Date: 2026-02-17 09:52:07.805119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c37c706819'
down_revision: Union[str, Sequence[str], None] = '8d92249df95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('editor_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_categories_id'), 'editor_categories', ['id'], unique=False)
    op.create_table('editor_cities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_cities_id'), 'editor_cities', ['id'], unique=False)
    op.create_table('user_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_links_id'), 'user_links', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('authors', sa.Column('date_of_birth', sa.DATE(), nullable=True))
    op.add_column('authors', sa.Column('highest_education', sa.String(length=50), nullable=True))
    op.add_column('authors', sa.Column('highest_education_other_specify', sa.String(length=100), nullable=True))
    op.add_column('authors', sa.Column('work_status', sa.String(length=50), nullable=True))
    op.add_column('authors', sa.Column('work_status_other_specify', sa.String(length=100), nullable=True))
    op.add_column('authors', sa.Column('city_id', sa.UUID(), nullable=True))
    op.add_column('authors', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('authors', sa.Column('onboarding_completed', sa.BOOLEAN(), nullable=True))
    op.create_foreign_key(None, 'authors', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'onboarding_completed')
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'city_id')
    op.drop_column('authors', 'work_status_other_specify')
    op.drop_column('authors', 'work_status')
    op.drop_column('authors', 'highest_education_other_specify')
    op.drop_column('authors', 'highest_education')
    op.drop_column('authors', 'date_of_birth')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_user_links_id'), table_name='user_links')
    op.drop_table('user_links')
    op.drop_index(op.f('ix_editor_cities_id'), table_name='editor_cities')
    op.drop_table('editor_cities')
    op.drop_index(op.f('ix_editor_categories_id'), table_name='editor_categories')
    op.drop_table('editor_categories')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
