"""added images array column in generated user stories table

Revision ID: 2b2b1a57d5bd
Revises: c8226590b016
Create Date: 2025-10-09 21:43:34.500094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b2b1a57d5bd'
down_revision: Union[str, Sequence[str], None] = 'c8226590b016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_user_stories', 'images')
    # ### end Alembic commands ###
