"""nlfsblsbslb

Revision ID: 2e1d7d65e202
Revises: 2f6708500945
Create Date: 2025-08-28 22:28:29.411738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e1d7d65e202'
down_revision: Union[str, Sequence[str], None] = '2f6708500945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories_raw', sa.Column('published_timestamp', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('stories_raw', 'published_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories_raw', sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('stories_raw', 'published_timestamp')
    # ### end Alembic commands ###
