"""fixed enum1

Revision ID: 2f6708500945
Revises: d3780b5f99fe
Create Date: 2025-08-28 20:46:58.759479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f6708500945'
down_revision: Union[str, Sequence[str], None] = 'd3780b5f99fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE location_level RENAME VALUE 'world' TO 'INTERNATIONAL'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'city' TO 'CITY'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'state' TO 'STATE'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'country' TO 'COUNTRY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE location_level RENAME VALUE 'INTERNATIONAL' TO 'world'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'CITY' TO 'city'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'STATE' TO 'state'")
    op.execute("ALTER TYPE location_level RENAME VALUE 'COUNTRY' TO 'country'")
    # ### end Alembic commands ###
