"""041220251401 added full text hash

Revision ID: 30baf265acd0
Revises: 13c7344f403c
Create Date: 2025-12-04 14:01:26.088325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30baf265acd0'
down_revision: Union[str, Sequence[str], None] = '13c7344f403c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('full_text_hash', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_generated_user_stories_title_hash'), table_name='generated_user_stories')
    op.create_index(op.f('ix_generated_user_stories_title_hash'), 'generated_user_stories', ['title_hash'], unique=True)
    op.create_index(op.f('ix_generated_user_stories_full_text_hash'), 'generated_user_stories', ['full_text_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_user_stories_full_text_hash'), table_name='generated_user_stories')
    op.drop_index(op.f('ix_generated_user_stories_title_hash'), table_name='generated_user_stories')
    op.create_index(op.f('ix_generated_user_stories_title_hash'), 'generated_user_stories', ['title_hash'], unique=False)
    op.drop_column('generated_user_stories', 'full_text_hash')
    # ### end Alembic commands ###
