"""added rejection reason column in user_stories

Revision ID: 38adddbada1c
Revises: f9f022ee8432
Create Date: 2025-09-12 15:38:18.015922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38adddbada1c'
down_revision: Union[str, Sequence[str], None] = 'f9f022ee8432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('rejection_reason', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'rejection_reason')
    # ### end Alembic commands ###
