"""added category and tags columns in user_generated_stories table

Revision ID: 3b9ffc61157b
Revises: 8f984c111a20
Create Date: 2025-09-29 16:41:24.787434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9ffc61157b'
down_revision: Union[str, Sequence[str], None] = '8f984c111a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('generated_user_stories', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_user_stories', 'tags')
    op.drop_column('generated_user_stories', 'category')
    # ### end Alembic commands ###
