"""renamed images column to images_keys in generated user stories column

Revision ID: 3bf510f5c01b
Revises: 20f82e6e599f
Create Date: 2025-10-10 00:20:06.352737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf510f5c01b'
down_revision: Union[str, Sequence[str], None] = '20f82e6e599f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('images_keys', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('generated_user_stories', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('generated_user_stories', 'images_keys')
    # ### end Alembic commands ###
