"""added user roles enum LOCAL

Revision ID: 3c14dc5e4d3a
Revises: 1994e2a8fee9
Create Date: 2025-09-25 13:39:14.256476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c14dc5e4d3a'
down_revision: Union[str, Sequence[str], None] = '1994e2a8fee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
