"""added updated_at column in generated_user_stories

Revision ID: 4c6763906313
Revises: 9e82822d5627
Create Date: 2025-09-17 17:23:15.001987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c6763906313'
down_revision: Union[str, Sequence[str], None] = '9e82822d5627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_user_stories', 'updated_at')
    # ### end Alembic commands ###
