"""made title hash column in generated user stories table nullable 211120251634

Revision ID: 4f761062896a
Revises: 14b623349711
Create Date: 2025-11-21 16:34:10.996821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f761062896a'
down_revision: Union[str, Sequence[str], None] = '14b623349711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'title_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_generated_user_stories_title_hash'), 'generated_user_stories', ['title_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_user_stories_title_hash'), table_name='generated_user_stories')
    op.alter_column('generated_user_stories', 'title_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
