"""made author id nullabe TEMP LOCAL

Revision ID: 57b398eb8ec5
Revises: b79b9414be12
Create Date: 2025-09-26 12:51:07.009545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b398eb8ec5'
down_revision: Union[str, Sequence[str], None] = 'b79b9414be12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'user_story_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('generated_user_stories', 'user_story_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
