"""added time diff interval in server_default 131020251442

Revision ID: 592224141680
Revises: 3bf510f5c01b
Create Date: 2025-10-13 14:42:44.289147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592224141680'
down_revision: Union[str, Sequence[str], None] = '3bf510f5c01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'created_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    op.alter_column('generated_user_stories', 'updated_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    
    op.alter_column('user_stories_answers', 'created_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    op.alter_column('user_stories_answers', 'updated_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    
    op.alter_column('user_stories_questions', 'created_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    
    op.alter_column('user_stories', 'created_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    op.alter_column('user_stories', 'updated_at',
                    server_default=sa.text("now() + INTERVAL '5 hours 30 minutes'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'created_at',
                    server_default=sa.text("now()"))
    op.alter_column('generated_user_stories', 'updated_at',
                    server_default=sa.text("now()"))
    
    op.alter_column('user_stories_answers', 'created_at',
                    server_default=sa.text("now()"))
    op.alter_column('user_stories_answers', 'updated_at',
                    server_default=sa.text("now()"))
    
    op.alter_column('user_stories_questions', 'created_at',
                    server_default=sa.text("now()"))
    
    op.alter_column('user_stories', 'created_at',
                    server_default=sa.text("now()"))
    op.alter_column('user_stories', 'updated_at',
                    server_default=sa.text("now()"))
    # ### end Alembic commands ###
