"""added tone, style, lang and word length in user_stories table

Revision ID: 59ca53cbfa6d
Revises: 6013de674f5e
Create Date: 2025-09-08 13:19:32.649030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ca53cbfa6d'
down_revision: Union[str, Sequence[str], None] = '6013de674f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    publish_status_enum = postgresql.ENUM('draft', 'generated', 'published', name='publish_status')
    publish_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('user_stories', sa.Column('tone', sa.String(length=50), nullable=True))
    op.add_column('user_stories', sa.Column('style', sa.String(length=50), nullable=True))
    op.add_column('user_stories', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('user_stories', sa.Column('word_length', sa.INTEGER(), nullable=True))
    op.add_column('user_stories', sa.Column('publish_status', publish_status_enum , nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'publish_status')
    op.drop_column('user_stories', 'word_length')
    op.drop_column('user_stories', 'language')
    op.drop_column('user_stories', 'style')
    op.drop_column('user_stories', 'tone')
    op.drop_column('user_stories', 'title')

    publish_status_enum = postgresql.ENUM('draft', 'generated', 'published', name='publish_status')
    publish_status_enum.create(op.get_bind())
    # ### end Alembic commands ###
