"""180220261221 (pressgenai)

Revision ID: 5e99808cba11
Revises: 23c37c706819
Create Date: 2026-02-18 12:21:59.397148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e99808cba11'
down_revision: Union[str, Sequence[str], None] = '23c37c706819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['generated_user_stories.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'category_id', name='unique_article_category')
    )
    op.create_index(op.f('ix_article_categories_id'), 'article_categories', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.create_unique_constraint('unique_editor_category', 'editor_categories', ['editor_id', 'category_id'])
    op.add_column('generated_user_stories', sa.Column('location_scope', sa.String(length=20), nullable=True))
    op.add_column('generated_user_stories', sa.Column('city_id', sa.UUID()))
    op.create_foreign_key(None, 'generated_user_stories', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_user_stories', type_='foreignkey')
    op.drop_column('generated_user_stories', 'city_id')
    op.drop_column('generated_user_stories', 'location_scope')
    op.drop_constraint('unique_editor_category', 'editor_categories', type_='unique')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_article_categories_id'), table_name='article_categories')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
