"""added tables for questions, answers and generated stories

Revision ID: 6013de674f5e
Revises: d05967b34c05
Create Date: 2025-09-02 16:44:18.172520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6013de674f5e'
down_revision: Union[str, Sequence[str], None] = 'd05967b34c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_user_stories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_story_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('snippet', sa.TEXT(), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_user_stories_id'), 'generated_user_stories', ['id'], unique=False)
    op.create_table('user_stories_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_story_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=True),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_questions_id'), 'user_stories_questions', ['id'], unique=False)
    op.create_table('user_stories_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_story_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['user_stories_questions.id'], ),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_answers_id'), 'user_stories_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_answers_id'), table_name='user_stories_answers')
    op.drop_table('user_stories_answers')
    op.drop_index(op.f('ix_user_stories_questions_id'), table_name='user_stories_questions')
    op.drop_table('user_stories_questions')
    op.drop_index(op.f('ix_generated_user_stories_id'), table_name='generated_user_stories')
    op.drop_table('generated_user_stories')
    # ### end Alembic commands ###
