"""added status flag column in questions table

Revision ID: 6857f911fa93
Revises: b6872677c532
Create Date: 2025-09-09 15:16:10.156614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6857f911fa93'
down_revision: Union[str, Sequence[str], None] = 'b6872677c532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories_questions', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories_questions', 'is_active')
    # ### end Alembic commands ###
