"""added title hash column

Revision ID: 6ff42a315339
Revises: 6eaccedb916f
Create Date: 2025-09-09 11:53:57.236708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff42a315339'
down_revision: Union[str, Sequence[str], None] = '6eaccedb916f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('title_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_stories_title_hash'), 'user_stories', ['title_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_title_hash'), table_name='user_stories')
    op.drop_column('user_stories', 'title_hash')
    # ### end Alembic commands ###
