"""added title hash columndsvsd

Revision ID: 78ffc4344a8b
Revises: 6ff42a315339
Create Date: 2025-09-09 12:04:10.763950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ffc4344a8b'
down_revision: Union[str, Sequence[str], None] = '6ff42a315339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'status',
               existing_type=postgresql.ENUM('collecting', 'drafting', 'completed', 'published', name='story_status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'status',
               existing_type=postgresql.ENUM('collecting', 'drafting', 'completed', 'published', name='story_status'),
               nullable=False)
    # ### end Alembic commands ###
