"""added a title slug column in generated stories table LOCAL

Revision ID: 7901d63068ed
Revises: bb201796de75
Create Date: 2025-10-04 13:59:08.553295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7901d63068ed'
down_revision: Union[str, Sequence[str], None] = 'bb201796de75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_generated_user_stories_slug'), 'generated_user_stories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_user_stories_slug'), table_name='generated_user_stories')
    op.drop_column('generated_user_stories', 'slug')
    # ### end Alembic commands ###
