"""added editor id foreign key in generated stories table LOCAL

Revision ID: 8f984c111a20
Revises: bd51f72b02a6
Create Date: 2025-09-28 22:05:03.981571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f984c111a20'
down_revision: Union[str, Sequence[str], None] = 'bd51f72b02a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('editor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generated_user_stories', 'users', ['editor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_user_stories', type_='foreignkey')
    op.drop_column('generated_user_stories', 'editor_id')
    # ### end Alembic commands ###
