"""changed description column to snippet

Revision ID: 9744ecdfbd66
Revises: dae7899bb750
Create Date: 2025-08-28 19:35:02.512345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9744ecdfbd66'
down_revision: Union[str, Sequence[str], None] = 'dae7899bb750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories_raw', sa.Column('snippet', sa.TEXT(), nullable=True))
    op.alter_column('stories_raw', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('stories_raw', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories_raw', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('stories_raw', 'published_date',
               existing_type=sa.DATE(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('stories_raw', 'snippet')
    # ### end Alembic commands ###
