"""added default field in author_id column1233

Revision ID: 9b126c2f6b7a
Revises: 28b10a615d6b
Create Date: 2025-09-22 17:31:09.570231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b126c2f6b7a'
down_revision: Union[str, Sequence[str], None] = '28b10a615d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('generated_user_stories', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
