"""added full text, full text hash and mode columns in user stories table1

Revision ID: 9e82822d5627
Revises: 38adddbada1c
Create Date: 2025-09-12 17:51:55.629803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e82822d5627'
down_revision: Union[str, Sequence[str], None] = '38adddbada1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('mode', sa.String(length=20), nullable=True))
    op.add_column('user_stories', sa.Column('full_text', sa.TEXT(), nullable=True, comment='The full article content for manual mode.'))
    op.add_column('user_stories', sa.Column('full_text_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_stories_full_text_hash'), 'user_stories', ['full_text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_full_text_hash'), table_name='user_stories')
    op.drop_column('user_stories', 'full_text_hash')
    op.drop_column('user_stories', 'full_text')
    op.drop_column('user_stories', 'mode')
    # ### end Alembic commands ###
