"""made last fetched timestamp nullable and added max days back column in locations table

Revision ID: afc200c88c96
Revises: 008bb1ce50e9
Create Date: 2025-08-21 15:08:27.281599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc200c88c96'
down_revision: Union[str, Sequence[str], None] = '008bb1ce50e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('max_days_back', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'max_days_back')
    # ### end Alembic commands ###
