"""added approved by and approved at columns in Users table 261120251650

Revision ID: b37cc1df325d
Revises: 10c50d4596cc
Create Date: 2025-11-26 16:50:11.424616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b37cc1df325d'
down_revision: Union[str, Sequence[str], None] = '10c50d4596cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by')
    # ### end Alembic commands ###
