"""added police stations table

Revision ID: b65985ae5b40
Revises: f74c168d55ef
Create Date: 2026-01-18 21:41:43.565163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = 'b65985ae5b40'
down_revision: Union[str, Sequence[str], None] = 'f74c168d55ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_stations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_police_stations_boundary', 'police_stations', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_police_stations_id'), 'police_stations', ['id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_police_stations_id'), table_name='police_stations')
    op.drop_index('idx_police_stations_boundary', table_name='police_stations', postgresql_using='gist')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
