"""made bio in authors table nullable LOCAL

Revision ID: b79b9414be12
Revises: 3c14dc5e4d3a
Create Date: 2025-09-25 13:48:38.925258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79b9414be12'
down_revision: Union[str, Sequence[str], None] = '3c14dc5e4d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
