"""added selectin mode in author_profile rel in Users model 01102025 LOCAL

Revision ID: bb201796de75
Revises: f1a3abdaeb56
Create Date: 2025-10-01 16:15:50.181300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb201796de75'
down_revision: Union[str, Sequence[str], None] = 'f1a3abdaeb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
