"""restored db

Revision ID: bfaffa5b4b92
Revises: 5ea8323f5a5d
Create Date: 2025-10-16 13:56:54.971027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfaffa5b4b92'
down_revision: Union[str, Sequence[str], None] = '5ea8323f5a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'user_story_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('generated_user_stories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_user_stories', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('generated_user_stories', 'user_story_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
