"""added user stories table

Revision ID: d05967b34c05
Revises: f56b87101cdb
Create Date: 2025-09-02 14:28:27.943867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd05967b34c05'
down_revision: Union[str, Sequence[str], None] = 'f56b87101cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', postgresql.ENUM('collecting', 'drafting', 'completed', 'published', name='story_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_context_hash'), 'user_stories', ['context_hash'], unique=True)
    op.create_index(op.f('ix_user_stories_id'), 'user_stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_id'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_context_hash'), table_name='user_stories')
    op.drop_table('user_stories')
    # ### end Alembic commands ###
