"""added country code column

Revision ID: d1bbe9806ae4
Revises: afc200c88c96
Create Date: 2025-08-22 17:26:37.342847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bbe9806ae4'
down_revision: Union[str, Sequence[str], None] = 'afc200c88c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('country_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'country_code')
    # ### end Alembic commands ###
