"""wip publish status & published at timestamp column added

Revision ID: da0d4392152c
Revises: 8a589f51e98e
Create Date: 2025-11-25 17:15:56.630688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0d4392152c'
down_revision: Union[str, Sequence[str], None] = '8a589f51e98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add the new enum value by recreating the type
    op.execute("ALTER TYPE user_story_publish_status RENAME TO user_story_publish_status_old")
    op.execute("CREATE TYPE user_story_publish_status AS ENUM ('pending', 'wip', 'published', 'rejected')")
    op.execute("ALTER TABLE user_stories ALTER COLUMN publish_status TYPE user_story_publish_status USING publish_status::text::user_story_publish_status")
    op.execute("DROP TYPE user_story_publish_status_old")
    
    op.add_column('generated_user_stories', sa.Column('published_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_user_stories', 'published_at')
    
    # Remove 'wip' from enum by recreating the type
    op.execute("ALTER TYPE user_story_publish_status RENAME TO user_story_publish_status_old")
    op.execute("CREATE TYPE user_story_publish_status AS ENUM ('pending', 'published', 'rejected')")
    op.execute("ALTER TABLE user_stories ALTER COLUMN publish_status TYPE user_story_publish_status USING publish_status::text::user_story_publish_status")
    op.execute("DROP TYPE user_story_publish_status_old")
    # ### end Alembic commands ###
