"""changed world to international in level enum column in locations table

Revision ID: dae7899bb750
Revises: e2d77c6d2364
Create Date: 2025-08-26 15:10:57.270924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae7899bb750'
down_revision: Union[str, Sequence[str], None] = 'e2d77c6d2364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
