"""nlfsblsbslb

Revision ID: def08d0192a2
Revises: 2e1d7d65e202
Create Date: 2025-08-29 13:12:14.725192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def08d0192a2'
down_revision: Union[str, Sequence[str], None] = '2e1d7d65e202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories_raw', 'thumbnail',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('stories_raw', 'link',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_unique_constraint(None, 'stories_raw', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories_raw', type_='unique')
    op.alter_column('stories_raw', 'link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('stories_raw', 'thumbnail',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
