"""added stories table

Revision ID: e2d77c6d2364
Revises: d1bbe9806ae4
Create Date: 2025-08-25 11:16:00.481855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2d77c6d2364'
down_revision: Union[str, Sequence[str], None] = 'd1bbe9806ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories_raw',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('thumbnail', sa.String(length=250), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('published_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_raw_id'), 'stories_raw', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_raw_id'), table_name='stories_raw')
    op.drop_table('stories_raw')
    # ### end Alembic commands ###
