"""added users table

Revision ID: ea60f8830000
Revises: 9b126c2f6b7a
Create Date: 2025-09-23 12:42:18.409255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea60f8830000'
down_revision: Union[str, Sequence[str], None] = '9b126c2f6b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('creator', 'editor', 'admin', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint(op.f('authors_password_key'), 'authors', type_='unique')
    op.drop_index(op.f('ix_authors_email'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.create_foreign_key(None, 'authors', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('authors', 'email')
    op.drop_column('authors', 'last_name')
    op.drop_column('authors', 'password')
    op.drop_column('authors', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('authors', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('authors', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_email'), 'authors', ['email'], unique=True)
    op.create_unique_constraint(op.f('authors_password_key'), 'authors', ['password'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
