"""made user relationship in authors table selectin

Revision ID: f1a3abdaeb56
Revises: 8fd44ef5a391
Create Date: 2025-09-30 15:37:30.625875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a3abdaeb56'
down_revision: Union[str, Sequence[str], None] = '8fd44ef5a391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
