"""removed enum type

Revision ID: f20be71fbed4
Revises: b8d907c0b1c6
Create Date: 2025-09-11 23:08:24.166166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f20be71fbed4'
down_revision: Union[str, Sequence[str], None] = 'b8d907c0b1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'status',
               existing_type=postgresql.ENUM('collecting', 'drafting', 'completed', 'published', 'generated', 'submitted', name='story_status'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('user_stories', 'publish_status',
               existing_type=postgresql.ENUM('draft', 'generated', 'published', 'pending', 'rejected', name='publish_status'),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'publish_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('draft', 'generated', 'published', 'pending', 'rejected', name='publish_status'),
               existing_nullable=True)
    op.alter_column('user_stories', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('collecting', 'drafting', 'completed', 'published', 'generated', 'submitted', name='story_status'),
               existing_nullable=True)
    # ### end Alembic commands ###
