"""nlfsblsbslbdfmobdjn

Revision ID: f56b87101cdb
Revises: def08d0192a2
Create Date: 2025-08-29 13:41:51.344650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56b87101cdb'
down_revision: Union[str, Sequence[str], None] = 'def08d0192a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stories_raw_link_key'), 'stories_raw', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stories_raw_link_key'), 'stories_raw', ['link'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
