"""nothing

Revision ID: f74c168d55ef
Revises: 30baf265acd0
Create Date: 2026-01-18 21:38:57.814499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74c168d55ef'
down_revision: Union[str, Sequence[str], None] = '30baf265acd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_user_stories', sa.Column('full_text_hash', sa.String(length=64), nullable=True), if_not_exists=True)
    op.drop_index(op.f('ix_generated_user_stories_title_hash'), table_name='generated_user_stories')
    op.create_index(op.f('ix_generated_user_stories_title_hash'), 'generated_user_stories', ['title_hash'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_generated_user_stories_full_text_hash'), 'generated_user_stories', ['full_text_hash'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_user_stories_full_text_hash'), table_name='generated_user_stories')
    op.drop_index(op.f('ix_generated_user_stories_title_hash'), table_name='generated_user_stories')
    op.create_index(op.f('ix_generated_user_stories_title_hash'), 'generated_user_stories', ['title_hash'], unique=False)
    op.drop_column('generated_user_stories', 'full_text_hash')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
